version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  allow:
  - dependency-name: Faithlife.Reflection
  - dependency-name: System.ComponentModel.Annotations
  - dependency-name: XmlDocMarkdown.Core
